apiVersion: v1
kind: Service
metadata:
  name: cnn-fastapi-service
spec:
  type: NodePort
  selector:
    app: cnn-fastapi
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007  # you can access via localhost:30007
